package dev.nodeterm.protocol.crypto

/**
 * The subset of TweetNaCl the phone protocol needs: `crypto_box` (Curve25519 + XSalsa20-Poly1305)
 * and its pieces. A faithful port of the public-domain TweetNaCl reference (the same code the
 * desktop runs as `tweetnacl` 1.0.3), so every box this produces opens there and vice versa —
 * `TweetNaclTest` pins that against vectors generated by the desktop's own library.
 *
 * Why a port rather than a provider: X25519 via `KeyAgreement("XDH")` only exists on Android 12+,
 * no platform provider exposes HSalsa20 (which `box.before` needs), and a hand-assembled
 * BouncyCastle chain would still need HSalsa20 written out. Two hundred lines that are checked
 * byte-for-byte against the other end are the smaller risk.
 *
 * Wire shape of `box.after` (tweetnacl-js `secretbox`): `mac(16) ‖ ciphertext`. The desktop's
 * `e2ee.encrypt` prepends the 24-byte nonce — see [NaclBox].
 */
internal object TweetNacl {
    const val KEY_BYTES = 32
    const val NONCE_BYTES = 24
    const val ZERO_BYTES = 32
    const val BOX_ZERO_BYTES = 16
    const val OVERHEAD_BYTES = ZERO_BYTES - BOX_ZERO_BYTES

    private val ZERO16 = ByteArray(16)
    private val NINE = ByteArray(32).also { it[0] = 9 }
    private val SIGMA = "expand 32-byte k".toByteArray(Charsets.US_ASCII)
    private val GF_121665 = longArrayOf(0xDB41, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)

    // ---- Salsa20 core ---------------------------------------------------------------------

    private fun ld32(x: ByteArray, i: Int): Int =
        (x[i].toInt() and 0xff) or
            ((x[i + 1].toInt() and 0xff) shl 8) or
            ((x[i + 2].toInt() and 0xff) shl 16) or
            ((x[i + 3].toInt() and 0xff) shl 24)

    private fun st32(x: ByteArray, j: Int, u: Int) {
        var v = u
        for (i in 0 until 4) {
            x[j + i] = (v and 0xff).toByte()
            v = v ushr 8
        }
    }

    private fun rotl(x: Int, c: Int): Int = (x shl c) or (x ushr (32 - c))

    private fun core(out: ByteArray, inp: ByteArray, inpOff: Int, k: ByteArray, c: ByteArray, h: Boolean) {
        val w = IntArray(16)
        val x = IntArray(16)
        val y = IntArray(16)
        val t = IntArray(4)
        for (i in 0 until 4) {
            x[5 * i] = ld32(c, 4 * i)
            x[1 + i] = ld32(k, 4 * i)
            x[6 + i] = ld32(inp, inpOff + 4 * i)
            x[11 + i] = ld32(k, 16 + 4 * i)
        }
        for (i in 0 until 16) y[i] = x[i]
        for (i in 0 until 20) {
            for (j in 0 until 4) {
                for (m in 0 until 4) t[m] = x[(5 * j + 4 * m) % 16]
                t[1] = t[1] xor rotl(t[0] + t[3], 7)
                t[2] = t[2] xor rotl(t[1] + t[0], 9)
                t[3] = t[3] xor rotl(t[2] + t[1], 13)
                t[0] = t[0] xor rotl(t[3] + t[2], 18)
                for (m in 0 until 4) w[4 * j + (j + m) % 4] = t[m]
            }
            for (m in 0 until 16) x[m] = w[m]
        }
        if (h) {
            for (i in 0 until 16) x[i] += y[i]
            for (i in 0 until 4) {
                x[5 * i] -= ld32(c, 4 * i)
                x[6 + i] -= ld32(inp, inpOff + 4 * i)
            }
            for (i in 0 until 4) {
                st32(out, 4 * i, x[5 * i])
                st32(out, 16 + 4 * i, x[6 + i])
            }
        } else {
            for (i in 0 until 16) st32(out, 4 * i, x[i] + y[i])
        }
    }

    private fun coreSalsa20(out: ByteArray, inp: ByteArray, k: ByteArray, c: ByteArray) =
        core(out, inp, 0, k, c, false)

    fun coreHSalsa20(out: ByteArray, inp: ByteArray, inpOff: Int, k: ByteArray, c: ByteArray) =
        core(out, inp, inpOff, k, c, true)

    /** XOR `b` bytes of `m` (or zeros when `m` is null) with the Salsa20 stream for nonce[nOff..nOff+8). */
    private fun streamSalsa20Xor(
        c: ByteArray, cposStart: Int, m: ByteArray?, mposStart: Int, bStart: Long,
        n: ByteArray, nOff: Int, k: ByteArray
    ) {
        var b = bStart
        if (b == 0L) return
        val z = ByteArray(16)
        val x = ByteArray(64)
        var cpos = cposStart
        var mpos = mposStart
        for (i in 0 until 8) z[i] = n[nOff + i]
        while (b >= 64) {
            coreSalsa20(x, z, k, SIGMA)
            for (i in 0 until 64) c[cpos + i] = ((if (m != null) m[mpos + i].toInt() else 0) xor x[i].toInt()).toByte()
            var u = 1
            for (i in 8 until 16) {
                u += z[i].toInt() and 0xff
                z[i] = (u and 0xff).toByte()
                u = u ushr 8
            }
            b -= 64
            cpos += 64
            if (m != null) mpos += 64
        }
        if (b > 0) {
            coreSalsa20(x, z, k, SIGMA)
            for (i in 0 until b.toInt()) c[cpos + i] = ((if (m != null) m[mpos + i].toInt() else 0) xor x[i].toInt()).toByte()
        }
    }

    private fun stream(c: ByteArray, d: Long, n: ByteArray, k: ByteArray) {
        val s = ByteArray(32)
        coreHSalsa20(s, n, 0, k, SIGMA)
        streamSalsa20Xor(c, 0, null, 0, d, n, 16, s)
    }

    private fun streamXor(c: ByteArray, m: ByteArray, d: Long, n: ByteArray, k: ByteArray) {
        val s = ByteArray(32)
        coreHSalsa20(s, n, 0, k, SIGMA)
        streamSalsa20Xor(c, 0, m, 0, d, n, 16, s)
    }

    // ---- Poly1305 (reference 17-limb form) ------------------------------------------------

    private val MINUS_P = intArrayOf(5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 252)

    private fun add1305(h: IntArray, c: IntArray) {
        var u = 0
        for (j in 0 until 17) {
            u += h[j] + c[j]
            h[j] = u and 255
            u = u ushr 8
        }
    }

    private fun onetimeauth(out: ByteArray, outPos: Int, m: ByteArray, mposStart: Int, nStart: Long, k: ByteArray) {
        val x = IntArray(17)
        val r = IntArray(17)
        val h = IntArray(17)
        val c = IntArray(17)
        val g = IntArray(17)
        for (j in 0 until 16) r[j] = k[j].toInt() and 0xff
        r[3] = r[3] and 15; r[4] = r[4] and 252; r[7] = r[7] and 15; r[8] = r[8] and 252
        r[11] = r[11] and 15; r[12] = r[12] and 252; r[15] = r[15] and 15
        var mpos = mposStart
        var n = nStart
        while (n > 0) {
            for (j in 0 until 17) c[j] = 0
            var j = 0
            while (j < 16 && j < n) {
                c[j] = m[mpos + j].toInt() and 0xff
                j++
            }
            c[j] = 1
            mpos += j
            n -= j
            add1305(h, c)
            for (i in 0 until 17) {
                var acc = 0
                for (jj in 0 until 17) {
                    acc += h[jj] * (if (jj <= i) r[i - jj] else 320 * r[i + 17 - jj])
                }
                x[i] = acc
            }
            for (i in 0 until 17) h[i] = x[i]
            var u = 0
            for (jj in 0 until 16) {
                u += h[jj]
                h[jj] = u and 255
                u = u ushr 8
            }
            u += h[16]
            h[16] = u and 3
            u = 5 * (u ushr 2)
            for (jj in 0 until 16) {
                u += h[jj]
                h[jj] = u and 255
                u = u ushr 8
            }
            u += h[16]
            h[16] = u
        }
        for (j in 0 until 17) g[j] = h[j]
        add1305(h, MINUS_P)
        val s = -(h[16] ushr 7)
        for (j in 0 until 17) h[j] = h[j] xor (s and (g[j] xor h[j]))
        for (j in 0 until 16) c[j] = k[j + 16].toInt() and 0xff
        c[16] = 0
        add1305(h, c)
        for (j in 0 until 16) out[outPos + j] = h[j].toByte()
    }

    private fun verify16(x: ByteArray, xi: Int, y: ByteArray, yi: Int): Boolean {
        var d = 0
        for (i in 0 until 16) d = d or ((x[xi + i].toInt() xor y[yi + i].toInt()) and 0xff)
        return d == 0
    }

    // ---- secretbox -------------------------------------------------------------------------

    /** tweetnacl-js `secretbox(msg, nonce, key)`: returns `mac(16) ‖ ciphertext`. */
    fun secretbox(msg: ByteArray, nonce: ByteArray, key: ByteArray): ByteArray {
        require(nonce.size == NONCE_BYTES) { "bad nonce size" }
        require(key.size == KEY_BYTES) { "bad key size" }
        val m = ByteArray(ZERO_BYTES + msg.size)
        System.arraycopy(msg, 0, m, ZERO_BYTES, msg.size)
        val c = ByteArray(m.size)
        streamXor(c, m, m.size.toLong(), nonce, key)
        onetimeauth(c, 16, c, 32, (m.size - 32).toLong(), c)
        return c.copyOfRange(BOX_ZERO_BYTES, c.size)
    }

    /** tweetnacl-js `secretbox.open`: null on a short box or a failed MAC. */
    fun secretboxOpen(box: ByteArray, nonce: ByteArray, key: ByteArray): ByteArray? {
        if (nonce.size != NONCE_BYTES || key.size != KEY_BYTES) return null
        val c = ByteArray(BOX_ZERO_BYTES + box.size)
        System.arraycopy(box, 0, c, BOX_ZERO_BYTES, box.size)
        if (c.size < 32) return null
        val x = ByteArray(32)
        stream(x, 32, nonce, key)
        val tag = ByteArray(16)
        onetimeauth(tag, 0, c, 32, (c.size - 32).toLong(), x)
        if (!verify16(c, 16, tag, 0)) return null
        val m = ByteArray(c.size)
        streamXor(m, c, c.size.toLong(), nonce, key)
        return m.copyOfRange(ZERO_BYTES, m.size)
    }

    // ---- Curve25519 -----------------------------------------------------------------------

    private fun car25519(o: LongArray) {
        for (i in 0 until 16) {
            o[i] += 1L shl 16
            val c = o[i] shr 16
            if (i < 15) o[i + 1] += c - 1 else o[0] += 38 * (c - 1)
            o[i] -= c shl 16
        }
    }

    private fun sel25519(p: LongArray, q: LongArray, b: Int) {
        val c = (b - 1).toLong().inv()
        for (i in 0 until 16) {
            val t = c and (p[i] xor q[i])
            p[i] = p[i] xor t
            q[i] = q[i] xor t
        }
    }

    private fun pack25519(o: ByteArray, n: LongArray) {
        val m = LongArray(16)
        val t = n.copyOf()
        car25519(t)
        car25519(t)
        car25519(t)
        for (j in 0 until 2) {
            m[0] = t[0] - 0xffed
            for (i in 1 until 15) {
                m[i] = t[i] - 0xffff - ((m[i - 1] shr 16) and 1)
                m[i - 1] = m[i - 1] and 0xffff
            }
            m[15] = t[15] - 0x7fff - ((m[14] shr 16) and 1)
            val b = ((m[15] shr 16) and 1).toInt()
            m[14] = m[14] and 0xffff
            sel25519(t, m, 1 - b)
        }
        for (i in 0 until 16) {
            o[2 * i] = (t[i] and 0xff).toByte()
            o[2 * i + 1] = (t[i] shr 8).toByte()
        }
    }

    private fun unpack25519(o: LongArray, n: ByteArray) {
        for (i in 0 until 16) o[i] = (n[2 * i].toLong() and 0xff) + ((n[2 * i + 1].toLong() and 0xff) shl 8)
        o[15] = o[15] and 0x7fff
    }

    private fun add(o: LongArray, a: LongArray, b: LongArray) {
        for (i in 0 until 16) o[i] = a[i] + b[i]
    }

    private fun sub(o: LongArray, a: LongArray, b: LongArray) {
        for (i in 0 until 16) o[i] = a[i] - b[i]
    }

    private fun mul(o: LongArray, a: LongArray, b: LongArray) {
        val t = LongArray(31)
        for (i in 0 until 16) for (j in 0 until 16) t[i + j] += a[i] * b[j]
        for (i in 0 until 15) t[i] += 38 * t[i + 16]
        for (i in 0 until 16) o[i] = t[i]
        car25519(o)
        car25519(o)
    }

    private fun sq(o: LongArray, a: LongArray) = mul(o, a, a)

    private fun inv25519(o: LongArray, i: LongArray) {
        val c = i.copyOf()
        for (a in 253 downTo 0) {
            sq(c, c)
            if (a != 2 && a != 4) mul(c, c, i)
        }
        for (a in 0 until 16) o[a] = c[a]
    }

    /** X25519: `q = n · p`. `n` is clamped here, exactly as the reference does. */
    fun scalarmult(q: ByteArray, n: ByteArray, p: ByteArray) {
        val z = ByteArray(32)
        for (i in 0 until 31) z[i] = n[i]
        z[31] = ((n[31].toInt() and 127) or 64).toByte()
        z[0] = (z[0].toInt() and 248).toByte()
        val x = LongArray(16)
        unpack25519(x, p)
        val a = LongArray(16)
        val b = x.copyOf()
        val c = LongArray(16)
        val d = LongArray(16)
        val e = LongArray(16)
        val f = LongArray(16)
        a[0] = 1
        d[0] = 1
        for (i in 254 downTo 0) {
            val r = ((z[i ushr 3].toInt() and 0xff) ushr (i and 7)) and 1
            sel25519(a, b, r)
            sel25519(c, d, r)
            add(e, a, c)
            sub(a, a, c)
            add(c, b, d)
            sub(b, b, d)
            sq(d, e)
            sq(f, a)
            mul(a, c, a)
            mul(c, b, e)
            add(e, a, c)
            sub(a, a, c)
            sq(b, a)
            sub(c, d, f)
            mul(a, c, GF_121665)
            add(a, a, d)
            mul(c, c, a)
            mul(a, d, f)
            mul(d, b, x)
            sq(b, e)
            sel25519(a, b, r)
            sel25519(c, d, r)
        }
        val x16 = a.copyOf()
        val x32 = c.copyOf()
        inv25519(x32, x32)
        mul(x16, x16, x32)
        pack25519(q, x16)
    }

    fun scalarmultBase(q: ByteArray, n: ByteArray) = scalarmult(q, n, NINE)

    /** tweetnacl-js `box.before(theirPublic, ourSecret)`. */
    fun boxBefore(publicKey: ByteArray, secretKey: ByteArray): ByteArray {
        require(publicKey.size == 32) { "bad public key size" }
        require(secretKey.size == 32) { "bad secret key size" }
        val s = ByteArray(32)
        scalarmult(s, secretKey, publicKey)
        val k = ByteArray(32)
        coreHSalsa20(k, ZERO16, 0, s, SIGMA)
        return k
    }
}
